import { Category } from './category';
import { Product } from './product';

export const PRODUCTS: Product[] = [
  {
    image: '../../assets/images/cropped/banana-puppy.jpg',
    thumb: '../../assets/images/thumbs/banana-puppy.jpg',
    title: 'Puppy Sized Banana Onesie',
    price: 24.99,
    description:
      'This adorable banana themed onesie is the perfect fit for your little furry friend. Machine washable. One-size fits small animals under 10 lbs.',
    tags: ['puppy', 'onesie', 'banana', 'clothing'],
    category: Category.CLOTHES,
    id: 'banana-puppy',
  },
  {
    image: '../../assets/images/cropped/bird-in-straw-hat.jpg',
    thumb: '../../assets/images/thumbs/bird-in-straw-hat.jpg',
    title: 'Straw Party Hat for Parakeets',
    price: 12.99,
    description:
      'This cute little purple, white, and green straw party hat will perfectly fit any parakeet sized bird. It is bio-degradable and non-toxic.',
    tags: ['bird', 'parakeet', 'hat', 'party', 'bio-degradable'],
    category: Category.HATS,
    id: 'bird-in-straw-hat',
  },
  {
    image: '../../assets/images/cropped/bowtie-dog.jpg',
    thumb: '../../assets/images/thumbs/bowtie-dog.jpg',
    title: 'Plaid Bowtie for Good Bois',
    price: 18.99,
    description:
      'Is your doggo the goodest boi? Prove it by giving them this very dapper wool plaid bowtie. This will also work for very large cats.',
    tags: ['dog', 'bowtie', 'wool', 'very large cats', 'business attire'],
    category: Category.OTHER,
    id: 'bowtie-dog',
  },
  {
    image: '../../assets/images/cropped/bird-teacup-hat.jpg',
    thumb: '../../assets/images/thumbs/bird-teacup-hat.jpg',
    title: 'Teacup Hat for Parakeets',
    price: 8.99,
    description:
      'Is this not just a regular teacup? Of course not, it is a bird sized tea cup that will perfectly fit any parakeet sized bird. It can also be used for bird tea parties.',
    tags: ['bird', 'parakeet', 'hat', 'party', 'teacup'],
    category: Category.HATS,
    id: 'bird-teacup-hat',
  },
  {
    image: '../../assets/images/cropped/cat-bonnet.jpg',
    thumb: '../../assets/images/thumbs/cat-bonnet.jpg',
    title: 'Baby Blue Baby Bonnet for Big Baby Kitties',
    price: 32.99,
    description:
      'This beautiful egg shell blue baby bonnet is purrrfect for all of your bestest babies. This bonnet is hand knit by midwestern grandmas.',
    tags: ['cat', 'bonnet', 'hat', 'baby', 'knit'],
    category: Category.HATS,
    id: 'cat-bonnet',
  },
  {
    image: '../../assets/images/cropped/cat-costume.jpg',
    thumb: '../../assets/images/thumbs/cat-costume.jpg',
    title: 'Puss In Boots for Kitty',
    price: 53.99,
    description:
      'This very fancy and totally era appropriate Puss In Boots themed outfit is just the thing to make your kitty stand out. ** Not responsible for murdered committed by angry cats **',
    tags: ['cat', 'outfit', 'costume', 'danger', 'adults-only'],
    category: Category.CLOTHES,
    id: 'cat-costume',
  },
  {
    image: '../../assets/images/cropped/cat-glasses-1.jpg',
    thumb: '../../assets/images/thumbs/cat-glasses-1.jpg',
    title: 'Dark Shades for Cool Cats',
    price: 12.99,
    description:
      "Your cat's future is so bright they need to wear shades. Dark shades.",
    tags: ['cat', 'dude', 'cool', 'sunglasses'],
    category: Category.GLASSES,
    id: 'cat-glasses-1',
  },
  {
    image: '../../assets/images/cropped/cat-glasses-2.jpg',
    thumb: '../../assets/images/thumbs/cat-glasses-2.jpg',
    title: 'Round Shiny Sunglasses for Cats Only',
    price: 15.99,
    description:
      'These sunglasses are only for cats. No dogs allowed. These glasses are too cool for dogs.',
    tags: ['cat', 'dude', 'cool', 'sunglasses'],
    category: Category.GLASSES,
    id: 'cat-glasses-2',
  },
  {
    image: '../../assets/images/cropped/cat-glasses-3.jpg',
    thumb: '../../assets/images/thumbs/cat-glasses-3.jpg',
    title: 'Morpheus Kitty Sunglasses',
    price: 18.99,
    description:
      'Is this the Matrix? Or is your cat just way more interesting than you are? Probably both.',
    tags: ['cat', 'dude', 'cool', 'sunglasses'],
    category: Category.GLASSES,
    id: 'cat-glasses-3',
  },
  {
    image: '../../assets/images/cropped/chef-cat.jpg',
    thumb: '../../assets/images/thumbs/chef-cat.jpg',
    title: 'Professional Chef Hat for Cats',
    price: 19.99,
    description:
      'Your cat just got their first job at the local bakery! Congratulations, they are going to need a hat.',
    tags: ['employed', 'cat', 'hat', 'chef', 'first job'],
    category: Category.HATS,
    id: 'chef-cat',
  },
  {
    image: '../../assets/images/cropped/cat-socks.jpg',
    thumb: '../../assets/images/thumbs/cat-socks.jpg',
    title: 'Tube Socks for Cats and Tiny Dogs',
    price: 9.99,
    description:
      'Keep their little tootsies warm with these adorable 80s inspired tube socks. Pull them up for extra knee coverage.',
    tags: ['cat', 'tiny dog', 'socks', '80s', 'tube socks'],
    category: Category.OTHER,
    id: 'cat-socks',
  },
  {
    image: '../../assets/images/cropped/chicken-arms.jpg',
    thumb: '../../assets/images/thumbs/chicken-arms.jpg',
    title: 'Buff Arms for Chickens',
    price: 25.99,
    description:
      "Are you tired of your chicken telling you they can't arm wrestle or lift heavy piles of logs? Well worry no more. These buff arms will make them look like a liar.",
    tags: ['chicken', 'buff', 'arms', 'get to work', 'fowl'],
    category: Category.OTHER,
    id: 'chicken-arms',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-2.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-2.jpg',
    title: 'Kurt Cobain Shades for Big Bois',
    price: 7.99,
    description:
      'Your doggo is the biggest boi and also super grunge. These very cool Kurt Cobain inspired sunglasses will let everyone know how cool and aloof your dog is.',
    tags: ['dog', 'sunglasses', 'nirvana', 'grunge', 'alternative'],
    category: Category.GLASSES,
    id: 'dog-glasses-2',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-3.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-3.jpg',
    title: 'Harry Pupper Glasses',
    price: 10.99,
    description:
      "You're a Wizard Pupper! and now you can have the round nerdy glasses to prove it.",
    tags: ['dog', 'glasses', 'nerd', 'wizard', 'brainy'],
    category: Category.GLASSES,
    id: 'dog-glasses-3',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-4.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-4.jpg',
    title: 'Mild Mannered Eager To Please Glasses For Doggos',
    price: 7.99,
    description:
      'Your doggo just wants to make you happy. And nothing makes people happier than making their eager to please puppers wear glasses.',
    tags: ['dog', 'glasses', 'mild mannered', 'pupper', 'nerd'],
    category: Category.GLASSES,
    id: 'dog-glasses-4',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-5.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-5.jpg',
    title: 'Cool Dude reflective Shades for Weiner Dogs',
    price: 14.99,
    description:
      'Their legs might be short but their cool is like four or five inches taller. These reflective shades look a lot cooler when they are reflecting palm trees.',
    tags: ['dog', 'sunglasses', 'reflective', 'cool', 'dude'],
    category: Category.GLASSES,
    id: 'dog-glasses-5',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-6.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-6.jpg',
    title: 'Intimidating Round Shades for Bulldogs',
    price: 18.99,
    description:
      'These glasses are aggressively intimidating. Is he sleeping? Is he staring? You will never ever know.',
    tags: ['dog', 'sunglasses', 'dark', 'cool', 'scary'],
    category: Category.GLASSES,
    id: 'dog-glasses-6',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-7.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-7.jpg',
    title: 'Professional Doggo Glasses',
    price: 18.99,
    description:
      'Whether they are starting their first day in IT or they are writing their first novel. These very professional glasses will give your doggo the confidence they need to succeed!',
    tags: ['dog', 'glasses', 'successful', 'professional', 'Sys Admin'],
    category: Category.GLASSES,
    id: 'dog-glasses-7',
  },
  {
    image: '../../assets/images/cropped/glasses-pom.jpg',
    thumb: '../../assets/images/thumbs/glasses-pom.jpg',
    title: 'Office Glasses for Tiny Dogs',
    price: 14.99,
    description:
      'Even toy breeds need to work, and what better way to look like you are fit for the job than to show up on your first day wearing glasses!',
    tags: ['dog', 'glasses', 'successful', 'professional', 'office work'],
    category: Category.GLASSES,
    id: 'glasses-pom',
  },
  {
    image: '../../assets/images/cropped/dog-yellow-boots.jpg',
    thumb: '../../assets/images/thumbs/dog-yellow-boots.jpg',
    title: 'Yellow Rubber Boots for Dogs',
    price: 23.99,
    description:
      'Keep their little tootsies warm and dry with these bright yellow rain boots. Not suitable for humans',
    tags: ['dog', 'boots', 'rain', 'not for people', 'very yellow'],
    category: Category.OTHER,
    id: 'dog-yellow-boots',
  },
  {
    image: '../../assets/images/cropped/hoodie-bulldog.jpg',
    thumb: '../../assets/images/thumbs/hoodie-bulldog.jpg',
    title: 'Hoodie for Tough Babies',
    price: 31.99,
    description:
      'No self respecting doggo would show up at the gym without this sweet Champion hoodie. Perfect for warm ups and cool downs.',
    tags: ['dog', 'hoodie', 'champion', 'gym rat', 'yellow'],
    category: Category.CLOTHES,
    id: 'hoodie-bulldog',
  },
  {
    image: '../../assets/images/cropped/jammie-cat.jpg',
    thumb: '../../assets/images/thumbs/jammie-cat.jpg',
    title: 'Kitty Baby Jam Jams',
    price: 11.99,
    description:
      'Snuggle up on cold days with this sweet fleece pajama top. Bottoms optional and also not recommended. For cats or little dogs.',
    tags: ['cat', 'pajamas', 'fleece', 'warm up', 'small dogs'],
    category: Category.CLOTHES,
    id: 'jammie-cat',
  },
  {
    image: '../../assets/images/cropped/lamb-jams.jpg',
    thumb: '../../assets/images/thumbs/lamb-jams.jpg',
    title: 'Baaa Baaa Baby Jammies',
    price: 18.99,
    description:
      'Wooly baby lambies need sweet soft jammies. Keep their little baby butts warm in these soft cotton flannel jam jams.',
    tags: ['flannel', 'pajama', 'sheep', 'lamb', 'cotton'],
    category: Category.CLOTHES,
    id: 'lamb-jams',
  },
  {
    image: '../../assets/images/cropped/overalls-puppy.jpg',
    thumb: '../../assets/images/thumbs/overalls-puppy.jpg',
    title: 'Denim Pooch Pants',
    price: 32.99,
    description:
      'These rugged and durable overalls are great for little poochies who work hard and play harder! Now with 100% more pockets!',
    tags: ['dog', 'work pants', 'overalls', 'denim', 'small dogs'],
    category: Category.CLOTHES,
    id: 'overalls-puppy',
  },
  {
    image: '../../assets/images/cropped/paper-crown-cat.jpg',
    thumb: '../../assets/images/thumbs/paper-crown-cat.jpg',
    title: 'Fancy Paper Crown for Kitty',
    price: 1.99,
    description:
      'This is literally made out of construction paper. Your cat is guaranteed to hate it.',
    tags: ['royalty', 'cat', 'paper', 'hat', 'crown'],
    category: Category.HATS,
    id: 'paper-crown-cat',
  },
  {
    image: '../../assets/images/cropped/parrot-suit.jpg',
    thumb: '../../assets/images/thumbs/parrot-suit.jpg',
    title: 'Bird Tuxedo',
    price: 65.99,
    description:
      "Your parakeet got invited to a wedding but he hasn't a thing to wear! Do not worry my fine feathered friend, this very classic tuxedo is the perfect thing!",
    tags: ['bird', 'tuxedo', 'formal', 'wedding', 'bowtie'],
    category: Category.CLOTHES,
    id: 'parrot-suit',
  },
  {
    image: '../../assets/images/cropped/party-cat.jpg',
    thumb: '../../assets/images/thumbs/party-cat.jpg',
    title: 'Party Hat for Cat',
    price: 3.99,
    description:
      'Nothing says party time like forcing your cat to wear a party hat! This party hat is made from cardboard and will totally annoy your cat for the entire three minutes they are wearing it.',
    tags: ['cat', 'party', 'hat', 'festive', 'annoying'],
    category: Category.HATS,
    id: 'party-cat',
  },
  {
    image: '../../assets/images/cropped/party-hat-cat.jpg',
    thumb: '../../assets/images/thumbs/party-hat-cat.jpg',
    title: 'Edible Party Hat for Cats',
    price: 5.99,
    description:
      "What is the best way to celebrate your dog's birthday? Get the cat an edible party hat! Yummers!",
    tags: ['cat', 'party', 'hat', 'edible', 'dogs'],
    category: Category.HATS,
    id: 'party-hat-cat',
  },
  {
    image: '../../assets/images/cropped/pig-dress.jpg',
    thumb: '../../assets/images/thumbs/pig-dress.jpg',
    title: 'Fairy Dress for Piggies',
    price: 31.99,
    description:
      'Hot pink tulle and polka dots will make any sweet piggy ready to party. Break out this lipstick and turn on the tunes!',
    tags: ['pig', 'dress', 'fairy', 'party', 'piggy'],
    category: Category.CLOTHES,
    id: 'pig-dress',
  },
  {
    image: '../../assets/images/cropped/pig-in-hat.jpg',
    thumb: '../../assets/images/thumbs/pig-in-hat.jpg',
    title: 'Cowboy Piggy Hat',
    price: 11.99,
    description:
      "Get along little piggy! That's what people are going to say when they see your pig wearing this cute little cowboy hat and bandana.",
    tags: ['pig', 'cowboy', 'western', 'bandana', 'piggy'],
    category: Category.CLOTHES,
    id: 'pig-in-hat',
  },
  {
    image: '../../assets/images/cropped/pig-in-skates.jpg',
    thumb: '../../assets/images/thumbs/pig-in-skates.jpg',
    title: 'Pig Skates',
    price: 43.99,
    description:
      'What could be cuter than a little pink piggy roller skating around the barnyard. These pink skates can handle any rough terrain and will last for years!',
    tags: ['pig', 'skates', 'roller skates', 'durable', 'pink'],
    category: Category.OTHER,
    id: 'pig-in-skates',
  },
  {
    image: '../../assets/images/cropped/pig-wig.jpg',
    thumb: '../../assets/images/thumbs/pig-wig.jpg',
    title: 'Pig Wig',
    price: 21.99,
    description:
      'No more embarrassing bald piggies in your house! This very fancy wig is made from real acrylic and can withstand ever the most vigorous mud bath.',
    tags: ['pig', 'wig', 'acrylic', 'fancy', 'piggy'],
    category: Category.OTHER,
    id: 'pig-wig',
  },
  {
    image: '../../assets/images/cropped/pink-crown-cat.jpg',
    thumb: '../../assets/images/thumbs/pink-crown-cat.jpg',
    title: 'Paper Kitty Crown',
    price: 1.99,
    description:
      'Yes. It is another paper crown for cats made out of construction paper. But this time it is pink. They will still hate it.',
    tags: ['cat', 'crown', 'paper', 'pink', 'party'],
    category: Category.HATS,
    id: 'pink-crown-cat',
  },
  {
    image: '../../assets/images/cropped/princess-piggy.jpg',
    thumb: '../../assets/images/thumbs/princess-piggy.jpg',
    title: 'Piggy Princess',
    price: 11.99,
    description:
      'Every little piggy is a princess! And you can make your little piggy feel like royalty with this little crown.',
    tags: ['piggy', 'crown', 'paper', 'royalty', 'party'],
    category: Category.HATS,
    id: 'princess-piggy',
  },
  {
    image: '../../assets/images/cropped/pug-booties.jpg',
    thumb: '../../assets/images/thumbs/pug-booties.jpg',
    title: 'Pug Uggs',
    price: 19.99,
    description: "Pug Uggs. For your dog's feet. These ones are black.",
    tags: ['dog', 'uggs', 'boots', 'black', 'cold'],
    category: Category.OTHER,
    id: 'pug-booties',
  },
  {
    image: '../../assets/images/cropped/red-hat-cat.jpg',
    thumb: '../../assets/images/thumbs/red-hat-cat.jpg',
    title: 'Red Party Hat for Cat',
    price: 3.99,
    description:
      'This party hat is red to match the level of anger your cat will feel inside when you make them wear this thing.',
    tags: ['cat', 'party', 'hat', 'festive', 'annoying'],
    category: Category.HATS,
    id: 'red-hat-cat',
  },
  {
    image: '../../assets/images/cropped/st-paddy-pig.jpg',
    thumb: '../../assets/images/thumbs/st-paddy-pig.jpg',
    title: 'Saint Patrick Pig Sunglassed',
    price: 18.99,
    description:
      'Kiss your pig! They are Irish! You can tell this pig is Irish because they are wearing green things and shamrock sunglasses.',
    tags: ['piggy', 'sunglasses', 'irish', 'leprechaun', 'party'],
    category: Category.GLASSES,
    id: 'st-paddy-pig',
  },
  {
    image: '../../assets/images/cropped/super-dog.jpg',
    thumb: '../../assets/images/thumbs/super-dog.jpg',
    title: 'Hero Dog Daily Wear',
    price: 19.99,
    description:
      'Your dog is ready to be the hero, but they are going to need a cape. This sleek little number fits nicely under any office wear and is comfortable enough to wear all day!',
    tags: ['dog', 'hero', 'super', 'cape', 'costume'],
    category: Category.CLOTHES,
    id: 'super-dog',
  },
  {
    image: '../../assets/images/cropped/sweater-cat.jpg',
    thumb: '../../assets/images/thumbs/sweater-cat.jpg',
    title: 'Red Sweater for Kitty',
    price: 13.99,
    description:
      'Keep kitty cozy all year round with this cute little red sweater. Roll up the sleeves to show everybody how cool your cat is.',
    tags: ['cat', 'sweater', 'winter', 'red', 'warm'],
    category: Category.CLOTHES,
    id: 'sweater-cat',
  },
  {
    image: '../../assets/images/cropped/ACC001.jpg',
    thumb: '../../assets/images/thumbs/ACC001.jpg',
    title: 'Dog Computer',
    id: 'ACC001',
    price: 12.99,
    description: 'Your dog needs a computer, and this is a computer!',
    quantity: 15,
    category: Category.Accessories,
    tags: ['computer', 'dog', 'technology', 'doggo'],
  },
  {
    image: '../../assets/images/cropped/ACC009.jpg',
    thumb: '../../assets/images/thumbs/ACC009.jpg',
    title: 'Poodle Ball Set',
    id: 'ACC009',
    price: 14.25,
    description:
      'Special ball for standard poodles only. Other dogs are not fancy enough for this ball',
    quantity: 22,
    category: Category.Toys,
    tags: ['toy set', 'ball', 'poodle', 'dogs', 'fancy'],
  },
  {
    image: '../../assets/images/cropped/ACC012.jpg',
    thumb: '../../assets/images/thumbs/ACC012.jpg',
    title: 'Cat Bed',
    id: 'ACC012',
    price: 39.99,
    description: 'Soft and plush bed for cats with removable cushion.',
    quantity: 10,
    category: Category.FURNITURE,
    tags: ['cat bed', 'soft', 'plush', 'removable cushion'],
  },
  {
    image: '../../assets/images/cropped/ACC015.jpg',
    thumb: '../../assets/images/thumbs/ACC015.jpg',
    title: 'Dog Ball',
    id: 'ACC015',
    price: 17.75,
    description: 'Colorful ball for dogs to play and hide.',
    quantity: 12,
    category: Category.Toys,
    tags: ['ball', 'dog toy', 'colorful'],
  },
  {
    image: '../../assets/images/cropped/ACC016.jpg',
    thumb: '../../assets/images/thumbs/ACC016.jpg',
    title: 'Cat Grooming Brush',
    id: 'ACC016',
    price: 11.25,
    description:
      'Soft-bristled brush for grooming cats with comfort grip handle.',
    quantity: 20,
    category: Category.Grooming,
    tags: ['grooming brush', 'cat accessory', 'soft-bristled', 'comfort grip'],
  },
  {
    image: '../../assets/images/cropped/ACC019.jpg',
    thumb: '../../assets/images/thumbs/ACC019.jpg',
    title: 'Cat Bedding Set',
    id: 'ACC019',
    price: 27.95,
    description:
      'Set of bedding for cats including fleece blankets and cushioned mats.',
    quantity: 6,
    category: Category.FURNITURE,
    tags: [
      'bedding set',
      'cat accessory',
      'fleece blankets',
      'cushioned mats',
    ],
  },
  {
    image: '../../assets/images/cropped/ACC026.jpg',
    thumb: '../../assets/images/thumbs/ACC026.jpg',
    title: 'Dog Dental Chews',
    id: 'ACC026',
    price: 8.99,
    description:
      'Dental chews for dogs to promote oral health and reduce tartar buildup.',
    quantity: 18,
    category: Category.Food,
    tags: ['dental chews', 'dog accessory', 'oral health', 'tartar buildup'],
  },
  {
    image: '../../assets/images/cropped/ACC032.jpg',
    thumb: '../../assets/images/thumbs/ACC032.jpg',
    title: 'Horse Grooming Kit',
    id: 'ACC032',
    price: 54.99,
    description:
      'Complete grooming kit for horses including brushes, curry comb, and hoof pick.',
    quantity: 10,
    category: Category.Grooming,
    tags: ['grooming kit', 'horse accessory', 'brushes', 'hoof pick'],
  },
  {
    image: '../../assets/images/cropped/ACC033.jpg',
    thumb: '../../assets/images/thumbs/ACC033.jpg',
    title: 'Princess Kitty Crown',
    id: 'ACC033',
    price: 19.5,
    description:
      'Beautiful 24k gold crown for your very special kitty cat',
    quantity: 15,
    category: Category.HATS,
    tags: ['cat', 'crown', 'real gold', 'princess'],
  },
  {
    image: '../../assets/images/cropped/ACC035.jpg',
    thumb: '../../assets/images/thumbs/ACC035.jpg',
    title: 'Pig Enclosure',
    id: 'ACC035',
    price: 24.99,
    description:
      'Rustic enclosure for pigs with large capacity and adjustable heights.',
    quantity: 12,
    category: Category.FURNITURE,
    tags: ['enclosure', 'pig accessory', 'automatic', 'adjustable height'],
  },
  {
    image: '../../assets/images/cropped/ACC037.jpg',
    thumb: '../../assets/images/thumbs/ACC037.jpg',
    title: 'Pig Pond',
    id: 'ACC037',
    price: 118.5,
    description: 'Interactive enrichment pond for pigs to play and exercise.',
    quantity: 20,
    category: Category.Toys,
    tags: ['enrichment pond', 'pig accessory', 'interactive', 'exercise'],
  },
  {
    image: '../../assets/images/cropped/ACC041.jpg',
    thumb: '../../assets/images/thumbs/ACC041.jpg',
    title: 'Pig Bedding',
    id: 'ACC041',
    price: 14.5,
    description: 'Soft bedding for pigs made from recycled materials.',
    quantity: 15,
    category: Category.FURNITURE,
    tags: ['bedding', 'pig accessory', 'soft', 'recycled materials'],
  },
  {
    image: '../../assets/images/cropped/ACC043.jpg',
    thumb: '../../assets/images/thumbs/ACC043.jpg',
    title: 'Decorated Cat Cookie',
    id: 'ACC043',
    price: 49.5,
    description:
      'If you really want your cat to hate you spend a bunch of money on this cute decorated cat cookie. We pick the message.',
    quantity: 15,
    category: Category.Food,
    tags: ['cat food', 'cookie', 'nutritious', 'vitamins', 'decorated'],
  },
  {
    image: '../../assets/images/cropped/ACC045.jpg',
    thumb: '../../assets/images/thumbs/ACC045.jpg',
    title: 'Another Dog Ball',
    id: 'ACC045',
    price: 17.99,
    description:
      'This ball looks like the other balls but we swear it is not just a tennis ball. It is an expensive tennis ball so it is better',
    quantity: 12,
    category: Category.Toys,
    tags: ['dog', 'dog accessories', 'ball', 'toys'],
  },
  {
    image: '../../assets/images/cropped/ACC047.jpg',
    thumb: '../../assets/images/thumbs/ACC047.jpg',
    title: 'Pig Collar',
    id: 'ACC047',
    price: 6.99,
    description:
      'Super cute piggie collar for your special little piggle',
    quantity: 20,
    category: Category.Accessories,
    tags: ['pig', 'durable', 'collar', 'CUTE!'],
  },
  {
    image: '../../assets/images/cropped/6.jpg',
    thumb: '../../assets/images/thumbs/6.jpg',
    title: 'Dog Grooming Kit',
    price: 36.78,
    description: 'Complete grooming kit for dogs.',
    tags: ['dog', 'grooming', 'kit'],
    category: Category.Grooming,
    id: '6',
    quantity: 80,
  },
  {
    image: '../../assets/images/cropped/10.jpg',
    thumb: '../../assets/images/thumbs/10.jpg',
    title: 'Reptile Heat Lamp',
    price: 42.34,
    description: 'Heat lamp for reptile enclosures.',
    tags: ['reptile', 'heat', 'lamp'],
    category: Category.Accessories,
    id: '10',
    quantity: 88,
  },
  {
    image: '../../assets/images/cropped/11.jpg',
    thumb: '../../assets/images/thumbs/11.jpg',
    title: 'Chameleon Twig',
    price: 25.99,
    description: 'It is a twig for your chameleon. It is special and you cannot find the same thing outside.',
    tags: ['lizard', 'chameleon', 'twig'],
    category: Category.FURNITURE,
    id: '11',
    quantity: 50,
  },
  {
    image: '../../assets/images/cropped/13.jpg',
    thumb: '../../assets/images/thumbs/13.jpg',
    title: 'Lizard Food Mix',
    price: 14.29,
    description: 'Nutritious food mix for lizards.',
    tags: ['lizard', 'food', 'mix'],
    category: Category.Food,
    id: '13',
    quantity: 73,
  },
  {
    image: '../../assets/images/cropped/15.jpg',
    thumb: '../../assets/images/thumbs/15.jpg',
    title: 'Lizard Climbing Branch',
    price: 15.49,
    description: 'Natural climbing branch for lizards.',
    tags: ['lizard', 'climbing', 'branch'],
    category: Category.FURNITURE,
    id: '15',
    quantity: 48,
  },
  {
    image: '../../assets/images/cropped/17.jpg',
    thumb: '../../assets/images/thumbs/17.jpg',
    title: 'Lizard Manicure',
    price: 35.67,
    description: 'Fancy lizard fingernails for fancy lizards. Includes nails and fancy superglue.',
    tags: ['lizard', 'fingernails', 'manicure'],
    category: Category.Accessories,
    id: '17',
    quantity: 38,
  },
  {
    image: '../../assets/images/cropped/19.jpg',
    thumb: '../../assets/images/thumbs/19.jpg',
    title: 'Lizard Habitat Kit',
    price: 120.45,
    description: 'Complete habitat kit for lizards.',
    tags: ['lizard', 'habitat', 'kit'],
    category: Category.FURNITURE,
    id: '19',
    quantity: 15,
  },
  {
    image: '../../assets/images/cropped/22.jpg',
    thumb: '../../assets/images/thumbs/22.jpg',
    title: 'Chameleon Sun Lamp',
    price: 32.99,
    description: 'Sun lamp to provide UV light for chameleons.',
    tags: ['chameleon', 'sun', 'lamp'],
    category: Category.Accessories,
    id: '22',
    quantity: 37,
  },
  {
    image: '../../assets/images/cropped/23.jpg',
    thumb: '../../assets/images/thumbs/23.jpg',
    title: 'Guinea Pig Food',
    price: 11.49,
    description: 'Nutritious and delicious guinea pig yum yums. Always fresh. Usually lettuce',
    tags: ['guinea pig', 'lettuce', 'food'],
    category: Category.Food,
    id: '23',
    quantity: 58,
  },
  {
    image: '../../assets/images/cropped/32.jpg',
    thumb: '../../assets/images/thumbs/32.jpg',
    title: 'Pig Feed',
    price: 18.75,
    description: 'Nutrient-rich feed formulated for pigs.',
    tags: ['pig', 'feed', 'nutritious'],
    category: Category.Food,
    id: '32',
    quantity: 65,
  },

  {
    image: '../../assets/images/cropped/34.jpg',
    thumb: '../../assets/images/thumbs/34.jpg',
    title: 'Dog Tooth Brush',
    price: 14.29,
    description: 'Soft-bristled brush for brushing dog teeth.',
    tags: ['dog', 'grooming', 'toothbrush', 'teef', 'dental'],
    category: Category.Grooming,
    id: '34',
    quantity: 78,
  },
  {
    image: '../../assets/images/cropped/35.jpg',
    thumb: '../../assets/images/thumbs/35.jpg',
    title: 'Pig Waterer',
    price: 32.59,
    description: 'Automatic waterer to keep pigs hydrated.',
    tags: ['pig', 'waterer', 'automatic'],
    category: Category.Accessories,
    id: '35',
    quantity: 29,
  },
  {
    image: '../../assets/images/cropped/36.jpg',
    thumb: '../../assets/images/thumbs/36.jpg',
    title: 'Cat Spa Day Set',
    price: 10.99,
    description: 'Super cute spa set for your cat! Cats are notorious for loving baths. Bathe your cat at your own risk.',
    tags: ['cat', 'spa day', 'towels'],
    category: Category.Grooming,
    id: '36',
    quantity: 56,
  },
  {
    image: '../../assets/images/cropped/37.jpg',
    thumb: '../../assets/images/thumbs/37.jpg',
    title: 'Puppy Play Ball',
    price: 15.49,
    description: 'Durable ball for puppies to play with. but not for big dogs. This is a puppy ball',
    tags: ['puppy', 'play', 'ball'],
    category: Category.Toys,
    id: '37',
    quantity: 34,
  },
  {
    image: '../../assets/images/cropped/38.jpg',
    thumb: '../../assets/images/thumbs/38.jpg',
    title: 'Dog Pie',
    price: 9.75,
    description: 'Delicious pie just for dogs! This pie is shoe leather flavored and totally healthy for your dog.',
    tags: ['dog', 'treats', 'delicious'],
    category: Category.Food,
    id: '38',
    quantity: 92,
  },
  {
    image: '../../assets/images/cropped/39.jpg',
    thumb: '../../assets/images/thumbs/39.jpg',
    title: 'Cat Shampoo',
    price: 19.99,
    description: 'Clean that stinky kitty with kitty shampoo! Safe for kitty eyes. Smells like clean.',
    tags: ['cat', 'shampoo', 'caution'],
    category: Category.Grooming,
    id: '39',
    quantity: 40,
  },
  {
    image: '../../assets/images/cropped/45.jpg',
    thumb: '../../assets/images/thumbs/45.jpg',
    title: 'Catnip Tea',
    price: 12.89,
    description: 'Get your cat high on life with delicious catnip tea!',
    tags: ['cat', 'tea', 'catnip'],
    category: Category.Food,
    id: '45',
    quantity: 70,
  },
  {
    image: '../../assets/images/cropped/47.jpg',
    thumb: '../../assets/images/thumbs/47.jpg',
    title: 'Doggie Bubble Bath',
    price: 11.29,
    description: 'Scrub a dub dub those stinky doggos with this blueberry scented bubble bath',
    tags: ['dog', 'bubble bath', 'gentle', 'blueberries'],
    category: Category.Grooming,
    id: '47',
    quantity: 77,
  },
  {
    image: '../../assets/images/cropped/49.jpg',
    thumb: '../../assets/images/thumbs/49.jpg',
    title: 'Claw Foot Bathtub for Dogs',
    price: 89.99,
    description: 'If you love your dog you will buy your dog his very own claw foot bathtub. Room sold separately',
    tags: ['dog', 'bathtime', 'bathtub'],
    category: Category.FURNITURE,
    id: '49',
    quantity: 20,
  },
  {
    image: '../../assets/images/cropped/50.jpg',
    thumb: '../../assets/images/thumbs/50.jpg',
    title: 'Doggo Digestive Aid',
    price: 15.75,
    description: 'Digestive aid to support doggo health.',
    tags: ['dog', 'digestive', 'aid'],
    category: Category.Food,
    id: '50',
    quantity: 63,
  },
  {
    image: '../../assets/images/cropped/52.jpg',
    thumb: '../../assets/images/thumbs/52.jpg',
    title: 'Cat Fruit',
    price: 18.49,
    description: 'You have heard of cat food but how about cat fruit! Sometimes cats will eat stuff like pomegranates. We will send you a fruit basket and your cat can eat it',
    tags: ['cat', 'fruit', 'food'],
    category: Category.Food,
    id: '52',
    quantity: 70,
  },
  {
    image: '../../assets/images/cropped/57.jpg',
    thumb: '../../assets/images/thumbs/57.jpg',
    title: 'Chinchilla Uno',
    price: 14.49,
    description: 'Uno cards for chinchillas! Because chinchillas are surprisingly good at Uno',
    tags: ['chinchilla', 'cards', 'toys'],
    category: Category.Toys,
    id: '57',
    quantity: 60,
  },
  {
    image: '../../assets/images/cropped/58.jpg',
    thumb: '../../assets/images/thumbs/58.jpg',
    title: 'Cat Food Bowl',
    price: 8.99,
    description: 'Sturdy food bowl for cats. It looks like a teacup so it is super cute',
    tags: ['cat', 'food', 'bowl'],
    category: Category.Accessories,
    id: '58',
    quantity: 80,
  },
  {
    image: '../../assets/images/cropped/59.jpg',
    thumb: '../../assets/images/thumbs/59.jpg',
    title: 'Chinchilla Treats',
    price: 10.49,
    description: 'Tasty treats made for chinchillas.',
    tags: ['chinchilla', 'treats', 'food'],
    category: Category.Food,
    id: '59',
    quantity: 75,
  },
  {
    image: '../../assets/images/cropped/64.jpg',
    thumb: '../../assets/images/thumbs/64.jpg',
    title: 'Tortoise Rocks',
    price: 45.99,
    description: 'Really big rocks for vary large tortoises.',
    tags: ['tortoise', 'not a turtle', 'rocks'],
    category: Category.FURNITURE,
    id: '64',
    quantity: 28,
  },
  {
    image: '../../assets/images/cropped/66.jpg',
    thumb: '../../assets/images/thumbs/66.jpg',
    title: 'Chinchilla Cooling Pad',
    price: 24.49,
    description: 'Cooling pad to keep chinchillas comfortable.',
    tags: ['chinchilla', 'cooling', 'pad'],
    category: Category.FURNITURE,
    id: '66',
    quantity: 33,
  },
  {
    image: '../../assets/images/cropped/67.jpg',
    thumb: '../../assets/images/thumbs/67.jpg',
    title: 'Chinchilla Vitamin C Supplement',
    price: 11.99,
    description: 'Vitamin C supplement for chinchillas.',
    tags: ['chinchilla', 'vitamin C', 'supplement'],
    category: Category.Food,
    id: '67',
    quantity: 55,
  },
];
